modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/Terrails/HealthOverlay/issues"
license = "MIT"

[[mods]]
modId = "healthoverlay"
version = "${version}"
displayName = "Health Overlay"
authors = "Terrails"
description = ''' A simple renderer for colored hearts '''
logoFile = "healthoverlay_icon.png"

[[dependencies.healthoverlay]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.healthoverlay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "CLIENT"